### ISSUE TITLE
Unable to save substance

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder23review#7] opened 2022-06-22 01:43 UTC
Hi Vince, 

Please watch the video below. I am unable to add substances after I have already added one substance. If I refresh the page, I can add it, but I can't add a second one. 

Here is the demo: 
https://www.loom.com/share/641879b60a5e4944b4f0dde490f6f3be

Here is the record: 

https://stage.hpd-collaborative.org/actions/builder/7265/record

Milla

**Comment by secondmanveran** [comment] 2022-06-22 15:16
@Millali 

Video not working.

**Comment by Millali** [comment] 2022-06-22 15:55
Here you go:

https://www.loom.com/share/e1dcb02d25d24ee9abc6daeb01cd9522

**Comment by secondmanveran** [comment] 2022-07-04 22:30
@Millali 

Added these 3 substances one after the other no issues:

<img width="880" alt="Screen Shot 2022-07-04 at 3 26 30 PM" src="https://user-images.githubusercontent.com/97000801/177222008-1dcef29f-a337-47d7-83d7-cf7a0e5e526d.png">

Added these 2 material one after the other, no issues:

<img width="852" alt="Screen Shot 2022-07-04 at 3 28 26 PM" src="https://user-images.githubusercontent.com/97000801/177222054-79888407-1ddd-4ecf-8cc4-c82fedcb6109.png">

I can't reproduce this issue any further.

**Comment by coryawhite** [comment] 2022-07-05 17:50
@Millali @secondmanveran 
Not sure if this belongs here or the other Substance/Material thread but I can save the Special Conditions but it will not show up after saving.  It is not in the preview either.

![image](https://user-images.githubusercontent.com/101753841/177386007-2436e32b-15fb-47c8-b229-b151ac562b7f.png)

**Comment by secondmanveran** [comment] 2022-07-06 03:23
Sounds like a user specific issue, I can't reproduce it.

**Comment by secondmanveran** [comment] 2022-07-06 05:23
This is a duplicate of issue #3 

Closing

**Closed by secondmanveran** 2022-07-06 05:23 UTC
Labels: done, works-4-me
